services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: storysmith-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GEMINI_AI_KEY: ${GEMINI_AI_KEY}

  frontend:
    image: storysmith-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: