name: Backend Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build and Test Backend
        working-directory: backend
        run: ./mvnw clean package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: storysmith-backend
          path: backend/target/*.jar

   